[package]
name = "chip8_emu"
version = "0.0.0"
authors = ["Michael Chesser"]

[[bin]]
name = "chip8_emu"
path = "src/main.rs"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"
